project:
  type: website
  output-dir: docs
  resources:
     - /**/img/*

website:
  title: "CB2EDU.ORG"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: 2023/cb2-101.qmd
        text: CB2-101
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



