project:
  type: website
  output-dir: docs
  resources:
     - /**/img/*

website:
  title: "CB2EDU.ORG"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cb2-101.html
        text: CB2-101
      - about.qmd
  body-footer: |
      ---
      <br><center><small>&copy; 2024 cb2edu.org. All rights reserved.</small></center>
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



